apiVersion: apps/v1
kind: Deployment
metadata:
  name: media
  namespace: media-center
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: media
  template:
    metadata:
      labels:
        app.kubernetes.io/name: media
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: shino
      runtimeClassName: nvidia
      securityContext:
        supplementalGroups:
          - 65537
        fsGroup: 65537
      initContainers:
        - name: chown
          image: alpine
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: plex-config
              mountPath: /data/plex-config
            - name: plex-config
              mountPath: /data/jellyfin-config
            - name: media
              mountPath: /data/media
            - name: plex-transcoding
              mountPath: /data/transcoding
          command:
            - sh
            - -c
            - (chmod 0775 /data/*; chown -R 1031:65537 /data/*; exit 0)
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-config
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: media
          persistentVolumeClaim:
            claimName: media-storage

        # Temp Dirs
        - name: plex-transcoding
          emptyDir: {}
        - name: jellyfin-transcoding
          emptyDir: {}
      containers:
        - name: plex
          image: linuxserver/plex
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Los_Angeles
            - name: PUID
              value: "1031"
            - name: PGID
              value: "65537"
            - name: VERSION
              value: "docker"
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: all
          livenessProbe:
            httpGet:
              path: /identity
              port: plex-https
              scheme: HTTPS
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /identity
              port: plex-https
              scheme: HTTPS
          ports:
            - containerPort: 32400
              name: plex-https
              hostPort: 32400
              protocol: TCP
            - containerPort: 32400
              name: plex-http-udp
              hostPort: 32400
              protocol: UDP
            - containerPort: 32469
              hostPort: 32469
              protocol: TCP
            - containerPort: 32469
              protocol: UDP
              hostPort: 32469
            - containerPort: 5353
              hostPort: 5353
              protocol: UDP
            - containerPort: 1900
              hostPort: 1900
              protocol: UDP
          volumeMounts:
            - name: plex-config
              mountPath: /config
            - name: media
              mountPath: /data/media
            - name: plex-transcoding
              mountPath: /transcoding
        - name: jellyfin
          image: linuxserver/jellyfin
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Los_Angeles
            - name: PUID
              value: "1031"
            - name: PGID
              value: "65537"
            - name: VERSION
              value: "docker"
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: all
          livenessProbe:
            httpGet:
              path: /health
              port: jellyfin-http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /health
              port: jellyfin-http
          ports:
            - containerPort: 8096
              name: jellyfin-http
              hostPort: 8096
              protocol: TCP
          volumeMounts:
            - name: jellyfin-config
              mountPath: /config
            - name: media
              mountPath: /data/media
            - name: jellyfin-transcoding
              mountPath: /transcoding
